# Generated by Django 4.2.5 on 2023-09-28 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='at_partner',
        ),
        migrations.AddField(
            model_name='grouping',
            name='at_partner',
            field=models.ManyToManyField(related_name='partner_groups', to=settings.AUTH_USER_MODEL, verbose_name='Группы товаров'),
        ),
        migrations.AddField(
            model_name='product',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_products', to=settings.AUTH_USER_MODEL, verbose_name='Товар партнера'),
        ),
        migrations.DeleteModel(
            name='ProductAtPartner',
        ),
    ]
