# Generated by Django 4.2.5 on 2023-10-03 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_remove_product_at_partner_grouping_at_partner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveSmallIntegerField(verbose_name='номер заказа')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('total_amount', models.PositiveIntegerField(verbose_name='Сумма заказа')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to=settings.AUTH_USER_MODEL, verbose_name='Наименование заказчика')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_orders', to=settings.AUTH_USER_MODEL, verbose_name='Наименование партнера')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='Количество продуктов')),
                ('summary', models.PositiveIntegerField(verbose_name='Сумма по продукту')),
                ('order_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_bill', to='product.order', verbose_name='Продукты по заказу')),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='product.product', verbose_name='Цена продукта')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bills_product', to='product.product', verbose_name='Наименование продуктов')),
            ],
        ),
    ]
